# Generated by Django 4.2.7 on 2025-09-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilda_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tilda UID')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.URLField(blank=True, verbose_name='Фото')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='SEO ключевые слова')),
                ('url', models.SlugField(blank=True, max_length=200, verbose_name='URL')),
                ('calculated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рассчитанная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BouquetComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='bouquets.bouquet', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Состав букета',
                'verbose_name_plural': 'Состав букетов',
            },
        ),
    ]
