# Generated by Django 4.2.7 on 2025-09-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquetcomposition',
            name='flower_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.floweritem', verbose_name='Элемент'),
        ),
    ]
