# Generated by Django 4.2.7 on 2025-09-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bouquets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='bouquetcomposition',
            unique_together={('bouquet', 'flower_item')},
        ),
    ]
