# Generated by Django 4.2.7 on 2025-09-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_sent_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_confirmed',
        ),
    ]
